[project]
name = "heber-modelo-api"
version = "0.1.0"
description = "Projeto Python bÃ¡sico para auxiliar no desenvolvimento da Heber-Modelo-Api"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pre-commit>=4.5.1",
]
