[plugins]
spotless = { id = "com.diffplug.spotless", version = "8.2.0" }
publish = { id = "com.vanniktech.maven.publish", version = "0.36.0" }
[libraries]
tomlj = { module = "org.tomlj:tomlj", version = "1.1.1" }
